# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.4'

services:
  ipfs:
    build:
      context: components/ceramic
      dockerfile: Dockerfile.ipfs-daemon
    ports:
      - ${IPFS_SWARM_PORT}:${IPFS_SWARM_PORT}
      - ${IPFS_SWARM_WS_PORT}:${IPFS_SWARM_WS_PORT}
      - ${IPFS_API_PORT}:${IPFS_API_PORT}
      - ${IPFS_GATEWAY_PORT}:${IPFS_GATEWAY_PORT}
      - ${IPFS_HEALTHCHECK_PORT}:${IPFS_HEALTHCHECK_PORT}
    volumes:
      - ${PWD}/data/ipfs:/root/.jsipfs
    command: >
      /bin/bash -c "
        [[ -d /root/.jsipfs/repo.lock ]] && rm -rf /root/.jsipfs/repo.lock;
        cd packages/ipfs-daemon
        ./lib/bin/ipfs-daemon.js
      "

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - ${GANACHE_PORT}:${GANACHE_PORT}
    volumes:
      - ./data/ganache:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'move sense much taxi wave hurry recall stairs thank brother nut woman'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - -l
      - '80000000'
      - --quiet
    depends_on:
      - ipfs

  # Ceramic anchor service is a PoC of anchor service according to the Ceramic specification.
  cas:
    build:
      context: components/cas
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/data/cas/data:/cas/data
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_MODE=${APP_MODE}
      - APP_PORT=${APP_PORT}
      - ANCHOR_SCHEDULE_EXPRESSION=${ANCHOR_SCHEDULE_EXPRESSION}
      - ANCHOR_EXPIRATION_PERIOD=${ANCHOR_EXPIRATION_PERIOD}
      - IPFS_API_URL=${IPFS_API_URL}

      - BLOCKCHAIN_CONNECTOR=${BLOCKCHAIN_CONNECTOR}
      - ETH_NETWORK=ganache
      - ETH_OVERRIDE_GAS_CONFIG=${ETH_OVERRIDE_GAS_CONFIG}
      - ETH_GAS_LIMIT=${ETH_GAS_LIMIT}
      - ETH_GAS_PRICE=${ETH_GAS_PRICE}
      - ETH_RPC_HOST=${ETH_RPC_HOST}
      - ETH_RPC_PORT=${ETH_RPC_PORT}
      - ETH_WALLET_PK=${ETH_WALLET_PK}

      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_SYNCHRONIZE=${TYPEORM_SYNCHRONIZE}
      - TYPEORM_LOGGING=${TYPEORM_LOGGING}
      - TYPEORM_ENTITIES=${TYPEORM_ENTITIES}
    depends_on:
      - ganache
      - ipfs
    command: >
      /bin/bash -c "
        while ! nc -z ganache 8545;
        do
          sleep 1;
        done;
        npm start
      "

  # Typescript implementation of the Ceramic protocol.
  ceramic:
    build:
      context: components/ceramic
      dockerfile: Dockerfile.daemon
    ports:
      - ${CERAMIC_DAEMON_PORT}:${CERAMIC_DAEMON_PORT}
    volumes:
      - ./data/ceramic:/root/.ceramic
    depends_on:
      - cas
      - ipfs
    command: >
      /bin/bash -c "
        while ! nc -z cas 8081;
        do
          sleep 1;
        done;
        cd packages/cli
        ./bin/ceramic.js daemon --debug --ipfs-api http://ipfs:5011 --anchor-service-api=http://cas:8081 --port ${CERAMIC_DAEMON_PORT}
      "
